# appspec.yml : CodeDeploy의 설정파일로, 배포 시점에 특정한 쉘을 실행시킬 수 있음.
# AppSpec 파일은 파일에 정의된 일련의 수명 주기 이벤트 후크로 각 배포를 관리하는 데 사용
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app # 인스턴스에서 파일이 저장될 위치
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall: # 설치가 된 이후에 deploy.sh 라는 스크립트 실행하도록 함
    - location: scripts/deploy.sh
      timeout: 60
      runas: root